FROM python:3.10-slim

WORKDIR /app

COPY app /app/app
COPY templates /app/templates
COPY static /app/static
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install langchain_community

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
